services:
  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: clickhouse
    ports:
      - "${DATABASE_DATA_PORT}:${DATABASE_DATA_PORT}"
      - "${DATABASE_METRIC_PORT}:${DATABASE_METRIC_PORT}"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DATABASE}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - ./clickhouse/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: [ "CMD", "clickhouse-client", "--query", "SELECT 1" ]
      interval: ${CLICKHOUSE_RETRIES}s
      retries: ${CLICKHOUSE_RETRIES}

  generator:
    container_name: generator
    env_file:
      - .env
    build:
      context: .
      dockerfile: ./generator/Dockerfile
    depends_on:
      clickhouse:
        condition: service_healthy
    restart: always

  grafana:
    image: grafana/grafana:10.4.0
    container_name: grafana
    ports:
      - "${GRAFANA_PORT:-3000}:${GRAFANA_PORT:-3000}"
    environment:
      GF_INSTALL_PLUGINS: grafana-clickhouse-datasource

      GF_SECURITY_ADMIN_USER: ${GRAFANA_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}

      GF_DATASOURCES_CLICKHOUSE_NAME: ClickHouse
      GF_DATASOURCES_CLICKHOUSE_TYPE: grafana-clickhouse-datasource
      GF_DATASOURCES_CLICKHOUSE_ACCESS: native
      GF_DATASOURCES_CLICKHOUSE_URL: http://${CLICKHOUSE_HOST}:${DATABASE_METRIC_PORT}
      GF_DATASOURCES_CLICKHOUSE_HOST: ${CLICKHOUSE_HOST}
      GF_DATASOURCES_CLICKHOUSE_ISDEFAULT: "true"
      GF_DATASOURCES_CLICKHOUSE_PORT: ${CLICKHOUSE_PORT}
      GF_DATASOURCES_CLICKHOUSE_DATABASE: ${CLICKHOUSE_DATABASE}
      GF_DATASOURCES_CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      GF_DATASOURCES_CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      clickhouse:
        condition: service_healthy
    user: "0"

  airflow:
    build: ./airflow
    container_name: airflow
    depends_on:
      clickhouse:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      AIRFLOW__CORE__LOAD_EXAMPLES: "False"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
    command: >
      bash -c " airflow db migrate && airflow users create --username admin --password admin --firstname admin --lastname admin --role Admin --email admin@test.com || true && airflow standalone "
    volumes:
      - ./airflow/dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
      - ./spark:/opt/spark
      - /var/run/docker.sock:/var/run/docker.sock

  spark-master:
    build: ./spark
    container_name: spark-master
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master --host spark-master --port 7077 --webui-port 8080
    ports:
      - "7077:7077"
      - "8081:8080"
    environment:
      - SPARK_MODE=master
    volumes:
      - ./spark/dags:/opt/spark/dags
      - ./data:/opt/airflow/data

  spark-worker-1:
    build: ./spark
    container_name: spark-worker-1
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark/dags:/opt/spark/dags
      - ./data:/opt/airflow/data

  spark-worker-2:
    build: ./spark
    container_name: spark-worker-2
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark/dags:/opt/spark/dags
      - ./data:/opt/airflow/data

  spark-worker-3:
    build: ./spark
    container_name: spark-worker-3
    depends_on:
      - spark-master
    environment:
      SPARK_MODE: worker
      SPARK_MASTER_URL: spark://spark-master:7077
    command: >
      /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    volumes:
      - ./spark/dags:/opt/spark/dags
      - ./data:/opt/airflow/data
