apiVersion: 1
datasources:
  - name: ClickHouse
    type: grafana-clickhouse-datasource
    uid: clickhouse
    jsonData:
      host: clickhouse
      port: 9000
      username: admin
      defaultDatabase: analytics
      protocol: native
    secureJsonData:
      password: admin123