apiVersion: 1
datasources:
  - name: ${GF_DATASOURCES_CLICKHOUSE_NAME}
    type: ${GF_DATASOURCES_CLICKHOUSE_TYPE}
    uid: ${GF_DATASOURCES_CLICKHOUSE_HOST}
    jsonData:
      host: ${GF_DATASOURCES_CLICKHOUSE_HOST}
      port: ${GF_DATASOURCES_CLICKHOUSE_PORT}
      username: ${GF_DATASOURCES_CLICKHOUSE_USER}
      defaultDatabase: ${GF_DATASOURCES_CLICKHOUSE_DATABASE}
      protocol: ${GF_DATASOURCES_CLICKHOUSE_ACCESS}
    secureJsonData:
      password: ${GF_DATASOURCES_CLICKHOUSE_PASSWORD}